#!/bin/sh
#
# wrapper script for vifm
# allows it to create image previews with ueberzug

set -e

# use nix stdenv.wrapProgram instead?
cleanup() {
    exec 3>&-
	rm "$FIFO_UEBERZUG"
}

trap cleanup HUP INT QUIT TERM PWR EXIT

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    vifm "$@"
else
    cachehome="${XDG_CACHE_HOME:-$HOME/.cache/}/vifm"
	[ ! -d "$cachehome" ] && mkdir -p "$cachehome"
	export FIFO_UEBERZUG="$cachehome/ueberzug-$$"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
	exec 3>"$FIFO_UEBERZUG"
    vifm "$@" 3>&-
fi
